"""fix created_at timestamp

Revision ID: a3a6fc79e098
Revises: 45117090eef4
Create Date: 2026-08-28 07:48:49.738617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3a6fc79e098'
down_revision: Union[str, Sequence[str], None] = '45117090eef4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions','created_at',
                existing_type=sa.DateTime(timezone=True),
                server_default=sa.func.now(),
                existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions','created_at',
                existing_type=sa.DateTime(timezone=True),
                server_default=None,
                existing_nullable=True)
    # ### end Alembic commands ###
